# Group 5 Final Project
# Data Driven Organizations
# Data Prep

In [4]:
# Importing the dataset and display the first 10 rows
import pandas as pd
graffiti = pd.read_csv('DSNY_Graffiti_Tracking.csv')
graffiti.head(10)

,INCIDENT_ADDRESS,BOROUGH,COMMUNITY_BOARD,POLICE_PRECINCT,CITY_COUNCIL_DISTRICT,BBL,CREATED_DATE,STATUS,RESOLUTION_ACTION,CLOSED_DATE,X_COORDINATE,Y_COORDINATE,LATITUDE,LONGITUDE,ZIP_CODE,CENSUS_TRACT,BIN,NTA,LOCATION
0,1183-flatbush-ave 1183-flatbush-ave,BROOKLYN,Unspecified BROOKLYN,Unspecified,NaN,NaN,12/20/19,Open,Property Research Required,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,119-01 NOSTRAND AVENUE,QUEENS,Unspecified QUEENS,Unspecified,NaN,NaN,1/14/19,Open,Property Research Required,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,BROOKLYN,Unspecified BROOKLYN,Unspecified,NaN,NaN,12/20/19,Open,Property Research Required,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,47 47 road,QUEENS,Unspecified QUEENS,Unspecified,NaN,NaN,1/29/19,Open,Property Research Required,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1702/ 86 ST,BROOKLYN,Unspecified BROOKLYN,Unspecified,NaN,NaN,1/1/20,Open,Property Research Required,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1301 Bruckner Boulevard,BRONX,Unspecified BRONX,Unspecified,NaN,NaN,9/21/19,Open,Property Research Required,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Attorney street,MANHATTAN,Unspecified MANHATTAN,Unspecified,NaN,NaN,6/18/19,Open,Property Research Required,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,323 third ave,BRONX,Unspecified BRONX,Unspecified,NaN,NaN,6/25/19,Open,Property Research Required,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,505 1/2 waverly avenue,BROOKLYN,Unspecified BROOKLYN,Unspecified,NaN,NaN,3/16/19,Open,Property Research Required,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,350 brooke avenue,BRONX,Unspecified BRONX,Unspecified,NaN,NaN,2/25/19,Open,Property Research Required,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Displaying the number of observations in the graffiti dataset
len(graffiti)

22140

In [7]:
# Getting general information about the graffiti dataset
graffiti.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22140 entries, 0 to 22139
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   INCIDENT_ADDRESS       22139 non-null  object
 1   BOROUGH                22140 non-null  object
 2   COMMUNITY_BOARD        22140 non-null  object
 3   POLICE_PRECINCT        22140 non-null  object
 4   CITY_COUNCIL_DISTRICT  20795 non-null  float64
 5   BBL                    20193 non-null  float64
 6   CREATED_DATE           22140 non-null  object
 7   STATUS                 22140 non-null  object
 8   RESOLUTION_ACTION      22140 non-null  object
 9   CLOSED_DATE            11191 non-null  object
 10  X_COORDINATE           20795 non-null  float64
 11  Y_COORDINATE           20795 non-null  float64
 12  LATITUDE               20765 non-null  float64
 13  LONGITUDE              20765 non-null  float64
 14  ZIP_CODE               20763 non-null  float64
 15  CENSUS_TRACT           20765 non-null  float64
 16  BIN                    20113 non-null  float64
 17  NTA                    20765 non-null  object
 18  LOCATION               20765 non-null  object
dtypes: float64(9), object(10)
memory usage: 3.2+ MB

In [11]:
# Getting the number of NULL values in the graffiti dataset
graffiti.isnull().sum()

INCIDENT_ADDRESS             1
BOROUGH                      0
COMMUNITY_BOARD              0
POLICE_PRECINCT              0
CITY_COUNCIL_DISTRICT     1345
BBL                       1947
CREATED_DATE                 0
STATUS                       0
RESOLUTION_ACTION            0
CLOSED_DATE              10949
X_COORDINATE              1345
Y_COORDINATE              1345
LATITUDE                  1375
LONGITUDE                 1375
ZIP_CODE                  1377
CENSUS_TRACT              1375
BIN                       2027
NTA                       1375
LOCATION                  1375
dtype: int64

As we can see, not even half of the observations in the dataset have complete data. We will extract the observations with complete data and see what that leaves us with.

In [12]:
# Dropping any rows with a NA in the dataset to ensure completeness of the data
graffiti_complete = graffiti.dropna()
graffiti_complete.head(10)

,INCIDENT_ADDRESS,BOROUGH,COMMUNITY_BOARD,POLICE_PRECINCT,CITY_COUNCIL_DISTRICT,BBL,CREATED_DATE,STATUS,RESOLUTION_ACTION,CLOSED_DATE,X_COORDINATE,Y_COORDINATE,LATITUDE,LONGITUDE,ZIP_CODE,CENSUS_TRACT,BIN,NTA,LOCATION
204,283 IRVING AVENUE,BROOKLYN,04 BROOKLYN,Precinct 83,37.0,3.033190e+09,7/16/19,Closed,Cleaning crew dispatched. Owner refused.,12/4/19,1007695.0,194184.0,40.699636,-73.915447,11237.0,441.0,3075943.0,Bushwick North,"(40.699636, -73.915447)"
205,121 DE KALB AVENUE,BROOKLYN,02 BROOKLYN,Precinct 88,35.0,3.020880e+09,5/23/19,Closed,Cleaning crew dispatched. Property cleaned.,11/6/19,990479.0,190583.0,40.689781,-73.977539,11201.0,33.0,3058410.0,Fort Greene,"(40.689781, -73.977539)"
207,461 FT WASHINGTON AVENUE,MANHATTAN,12 MANHATTAN,Precinct 34,10.0,1.021770e+09,6/20/19,Closed,Cleaning crew dispatched. Property cleaned.,11/19/19,1001292.0,249197.0,40.850598,-73.938421,10033.0,265.0,1064298.0,Washington Heights South,"(40.850598, -73.938421)"
210,111-75 44 AVENUE,QUEENS,04 QUEENS,Precinct 110,21.0,4.020160e+09,2/14/19,Closed,Cleaning crew dispatched. Property cleaned.,3/25/19,1024726.0,212235.0,40.749120,-73.853918,11368.0,399.0,4000000.0,Corona,"(40.74912, -73.853918)"
211,2404 CONEY ISLAND AVENUE,BROOKLYN,15 BROOKLYN,Precinct 61,47.0,3.071120e+09,3/21/19,Closed,Cleaning crew dispatched. Owner refused.,7/17/19,995018.0,157385.0,40.598655,-73.961225,11223.0,394.0,3192205.0,Homecrest,"(40.598655, -73.961225)"
213,12 WESTCHESTER SQUARE,BRONX,10 BRONX,Precinct 45,13.0,2.039810e+09,2/21/19,Closed,Cleaning crew dispatched. No graffiti on prope...,5/14/19,1027604.0,245436.0,40.840352,-73.843316,10461.0,200.0,2041857.0,Van Nest-Morris Park-Westchester Square,"(40.840352, -73.843316)"
214,110-05 101 AVENUE,QUEENS,09 QUEENS,Precinct 102,28.0,4.094120e+09,6/21/19,Closed,Cleaning crew dispatched. Property cleaned.,12/23/19,1030442.0,189922.0,40.687849,-73.833441,11419.0,118.0,4197958.0,Richmond Hill,"(40.687849, -73.833441)"
217,23 MONROE STREET,MANHATTAN,03 MANHATTAN,Precinct 5,1.0,1.002760e+09,1/15/19,Closed,Cleaning crew dispatched. Property cleaned.,5/7/19,985496.0,198490.0,40.711486,-73.995506,10002.0,8.0,1003294.0,Chinatown,"(40.711486, -73.995506)"
220,44 LEE AVENUE,BROOKLYN,01 BROOKLYN,Precinct 90,33.0,3.021820e+09,4/24/19,Closed,Cleaning crew dispatched. Property cleaned.,10/22/19,995174.0,196598.0,40.706286,-73.960599,11211.0,535.0,3059952.0,Williamsburg,"(40.706286, -73.960599)"
222,353 BROADWAY,BROOKLYN,01 BROOKLYN,Precinct 90,34.0,3.024620e+09,5/13/19,Closed,Cleaning crew dispatched. Property cleaned.,10/7/19,996515.0,197106.0,40.707679,-73.955762,11211.0,527.0,3063593.0,North Side-South Side,"(40.707679, -73.955762)"

In [13]:
# Displaying the new number of observations in the dataset
len(graffiti_complete)

11056

In [14]:
# Getting general information about the dataset
graffiti_complete.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11056 entries, 204 to 22139
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   INCIDENT_ADDRESS       11056 non-null  object
 1   BOROUGH                11056 non-null  object
 2   COMMUNITY_BOARD        11056 non-null  object
 3   POLICE_PRECINCT        11056 non-null  object
 4   CITY_COUNCIL_DISTRICT  11056 non-null  float64
 5   BBL                    11056 non-null  float64
 6   CREATED_DATE           11056 non-null  object
 7   STATUS                 11056 non-null  object
 8   RESOLUTION_ACTION      11056 non-null  object
 9   CLOSED_DATE            11056 non-null  object
 10  X_COORDINATE           11056 non-null  float64
 11  Y_COORDINATE           11056 non-null  float64
 12  LATITUDE               11056 non-null  float64
 13  LONGITUDE              11056 non-null  float64
 14  ZIP_CODE               11056 non-null  float64
 15  CENSUS_TRACT           11056 non-null  float64
 16  BIN                    11056 non-null  float64
 17  NTA                    11056 non-null  object
 18  LOCATION               11056 non-null  object
dtypes: float64(9), object(10)
memory usage: 1.7+ MB

In [15]:
# Calculating the number of NULL values in the dataset
graffiti_complete.isnull().sum()

INCIDENT_ADDRESS         0
BOROUGH                  0
COMMUNITY_BOARD          0
POLICE_PRECINCT          0
CITY_COUNCIL_DISTRICT    0
BBL                      0
CREATED_DATE             0
STATUS                   0
RESOLUTION_ACTION        0
CLOSED_DATE              0
X_COORDINATE             0
Y_COORDINATE             0
LATITUDE                 0
LONGITUDE                0
ZIP_CODE                 0
CENSUS_TRACT             0
BIN                      0
NTA                      0
LOCATION                 0
dtype: int64

As we can see, we have dropped all observations with NAs in them. Thus, we are left with only the observations with complete data.

In [18]:
# Displaying the final dataset
graffiti_complete

,INCIDENT_ADDRESS,BOROUGH,COMMUNITY_BOARD,POLICE_PRECINCT,CITY_COUNCIL_DISTRICT,BBL,CREATED_DATE,STATUS,RESOLUTION_ACTION,CLOSED_DATE,X_COORDINATE,Y_COORDINATE,LATITUDE,LONGITUDE,ZIP_CODE,CENSUS_TRACT,BIN,NTA,LOCATION
204,283 IRVING AVENUE,BROOKLYN,04 BROOKLYN,Precinct 83,37.0,3.033190e+09,7/16/19,Closed,Cleaning crew dispatched. Owner refused.,12/4/19,1007695.0,194184.0,40.699636,-73.915447,11237.0,441.0,3075943.0,Bushwick North,"(40.699636, -73.915447)"
205,121 DE KALB AVENUE,BROOKLYN,02 BROOKLYN,Precinct 88,35.0,3.020880e+09,5/23/19,Closed,Cleaning crew dispatched. Property cleaned.,11/6/19,990479.0,190583.0,40.689781,-73.977539,11201.0,33.0,3058410.0,Fort Greene,"(40.689781, -73.977539)"
207,461 FT WASHINGTON AVENUE,MANHATTAN,12 MANHATTAN,Precinct 34,10.0,1.021770e+09,6/20/19,Closed,Cleaning crew dispatched. Property cleaned.,11/19/19,1001292.0,249197.0,40.850598,-73.938421,10033.0,265.0,1064298.0,Washington Heights South,"(40.850598, -73.938421)"
210,111-75 44 AVENUE,QUEENS,04 QUEENS,Precinct 110,21.0,4.020160e+09,2/14/19,Closed,Cleaning crew dispatched. Property cleaned.,3/25/19,1024726.0,212235.0,40.749120,-73.853918,11368.0,399.0,4000000.0,Corona,"(40.74912, -73.853918)"
211,2404 CONEY ISLAND AVENUE,BROOKLYN,15 BROOKLYN,Precinct 61,47.0,3.071120e+09,3/21/19,Closed,Cleaning crew dispatched. Owner refused.,7/17/19,995018.0,157385.0,40.598655,-73.961225,11223.0,394.0,3192205.0,Homecrest,"(40.598655, -73.961225)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22130,1881 BELMONT AVENUE,BRONX,06 BRONX,Precinct 48,17.0,2.029470e+09,4/24/19,Closed,Cleaning crew dispatched. Property cleaned.,10/16/19,1013847.0,247021.0,40.844641,-73.893028,10457.0,36901.0,2113038.0,East Tremont,"(40.844641, -73.893028)"
22132,402 EAST 148 STREET,BRONX,01 BRONX,Precinct 40,8.0,2.022920e+09,1/24/19,Closed,Cleaning crew dispatched. Property cleaned.,3/14/19,1006998.0,236281.0,40.815183,-73.917818,10455.0,43.0,2000515.0,Mott Haven-Port Morris,"(40.815183, -73.917818)"
22137,866 AVENUE OF THE AMERICAS,MANHATTAN,05 MANHATTAN,Precinct 14,3.0,1.008320e+09,1/17/19,Closed,Cleaning crew dispatched. No graffiti on prope...,5/21/19,987213.0,211680.0,40.747607,-73.989364,10001.0,76.0,1015777.0,Midtown-Midtown South,"(40.747607, -73.989364)"
22138,623 NOSTRAND AVENUE,BROOKLYN,08 BROOKLYN,Precinct 77,36.0,3.012200e+09,5/2/19,Closed,Cleaning crew dispatched. Property cleaned.,8/2/19,998137.0,185481.0,40.675769,-73.949935,11216.0,315.0,3030707.0,Crown Heights North,"(40.675769, -73.949935)"
22139,2454 WEBB AVENUE,BRONX,07 BRONX,Precinct 52,14.0,2.032190e+09,6/24/19,Closed,Cleaning crew dispatched. Property cleaned.,11/15/19,1010272.0,254523.0,40.865243,-73.905920,10468.0,263.0,2014764.0,Kingsbridge Heights,"(40.865243, -73.90592)"